### ISSUE TITLE
86Box broken many 286/386SX PC emulation since rev #860

### ISSUE THREAD

**Issue by greatpsycho** [OBattler/86Box#138]
When I use 286/386SX PC emulation like IBM AT, 86Box crashes when memory size change. After crashes, memory size shows minimum size in 86Box Setting dialog but always maximum size applied.

And mem_remap_top_384k() function should not be called AT NEAT, AT SCAT, AT Headland chipset initialization in model.c because that chipsets support shadow ram and can alter memory remapping feature via chipset-spectific register.

**Comment by OBattler** [comment]
Looks like an UI bug, the memory size is not being set correctly. I'm going to look into that. And I'll also remove mem_remap_top_384k() from those machines' init functions.

**Comment by OBattler** [comment]
I just committed a fix for both these issues. You may have to edit the configuration file though, to sanitize the memory size there because the emulator was incorrectly multiplying memory size by 1024 for those boards, resulting in memory size being set to eg. 16777216 (for 16384 in Settings) which is 16 GB (hence the crash as that's way beyond what a 32-bit process can take).
