### ISSUE TITLE
Trademarking the 86Box intellectual property

### ISSUE THREAD

**Issue by ghost** [OBattler/86Box#181]
I couldn't find a forum for 86Box. Other significant programming projects establish an active forum so that there is documentation of widespread use of the software/property. This may lead to trademarking both of the name of the forum and the program itself, such as 86Box. If the code is GPL, then the idea behind the code is already publicly available, but the recognition of the actual project could be protected under a trademark name. This provides protection against others trying to duplicate your effort.

https://en.wikipedia.org/wiki/Trademark
"A trademark (...) is a recognizable sign, design, or expression which identifies products or services of a particular source from those of others..."

For example, Doom is a trademarked name.

A business then could negotiate for use of your product and for a support contract. There are numerous examples of this in the emulation community and also of companies who establish partnerships with them.

**Comment by BoisterousSleet75** [comment]
Do you come to this wrong project?

**Comment by BoisterousSleet75** [comment]
Do you know #softhistory IRC?

**Comment by BoisterousSleet75** [comment]
> I couldn't find a forum for 86Box
I think you should join the IRC Channel: [https://kiwiirc.com/client/irc.rol.im/?nick=86box%7C?#softhistory](https://kiwiirc.com/client/irc.rol.im/?nick=86box%7C?#softhistory)

**Comment by BoisterousSleet75** [comment]
Also, I'm not sure if @OBattler could trademarking 86Box as an intellectual property.

**Comment by MoochMcGee** [comment]
Why the FUCK would we trademark a fucking open-source emulator built for
preservation? WHY?! Give me one good fucking reason.

**Comment by claunia** [comment]
Issuer has everything quite confused.

The intellectual property, called copyright, is automatically given to all the developers of the code collectively called 86Box.

The trademark, is the name or logotype identifying a product of service, in this case this would be “86Box”. Nonetheless there are cases where a trademark doesnt need to be applied (in this case because 86Box is part of the previous copyright, in the same case as the name of a book is protected even if it’s not a registered trademark).

Also there’s the case of a registered vs unregistered trademark, but that’s something not needed to be explained here.

Finally all use cases named by the issuer are wrong:
1.- Some other trademarking 86Box in the realm of “computer software or hardware” will get its trademark invalidated for copyright infringement.
2.- Trademark does not protect ideas. Copyright protect creations, trademark protect public recognition and patents protect ways to solve a problem. Nothing protects “ideas”.
3.- GPL has nothing to do with “publicly”. You can have GPL projects that are private.
4.- Having business, or support contracts, or any other case or monetization, does not require trademark or even being the copyright owner. Red Hat provides both for Linux and is not the registrar of either.

**Comment by waltje** [comment]
Hi,

> I couldn't find a forum for 86Box.
At this time, 86Box does not have a web-based forum- instead,
all support and discussion is handled on the #softhist channel
of the irc.ringoflightning.net IRC network.

>  Other significant programming projects establish an active
> forum so that there is documentation of widespread use of
> the software/property.
Not necessarily the case.  I have been part of many very large
projects, none of which had a forum.

> This may lead to trademarking both of the name of the forum
> and the program itself, such as 86Box.
No. According to the (current) rules of the U.S. Patent and
Trademark Office (which is on my end of the project), as well
as the European Trademark Bureau (which is on Battler's
end of the project), any claim to a trademark requires a fairly
extensive motivation of why you think you'd be entitled to
that trade mark.  Just showing a forum with that name does
not imply rights.

> If the code is GPL, then the idea behind the code is already
> publicly available, but the recognition of the actual project
> could be protected under a trademark name.
No.  You can not request a trademark (and/or registered
trademark, which is slightly different) on an implementation
(of an idea.)  You could do so for its NAME, but not for the
actual implementation, regardless of whether or not that is
based on a closed- or open-source model.

Since 86Box is based on the PCem project (although lesser
and lesser with every release..), that would also be an issue.

Likewise, Sarah (the author of PCem) could not "trademark"
her project, for the same reasons as above. She could do so
for the *name* of PCem, but not for the project itself. She could
try to claim rights for her Dynamic Recompiler, but, again, that
is "just another" implementation of a JIT code recompiler, and,
as such, not eligble for a claim.

Although some really nifty ideas come up in writing emulators
like this, none of those can be *trademarked* easily, other than
their names.  Claiming copyrights is possible, on selected parts
of the project, but can be very hard to maintain in a court of
law, as it's usually a mix of various sources of code, with
varying re-use licenses.

> This provides protection against others trying to duplicate your effort.
It does not.  A trademark, as your Wiki quote says, provides a
certain degree of protection for a NAME or recognizable SIGN
(logo, icon, flag, banner, certain way of spelling or use of a font,
etc) of something, not the actual project itself.

Since this is an open-source project, its (summary of) re-distribution
and re-use licenses define who can do what with it.  Authors of
individual modules can (and do) claim rights to those modules,
to protect their work.  Anyone could grab a copy of 86Box, modify
it, and then re-distribute it, provided:

- they do not violate any of the licenses used in the actual code of
  the project; and

- they do not use the same project name, if (and only if) there is a
  trade mark registered on that name, or pending registration.

Both issues ARE being looked in to, by the way.

Regards,

Fred N. van Kempen ("waltje")
