### ISSUE TITLE
Requests - January 2018

### ISSUE THREAD

**Issue by ArtiomWin** [OBattler/86Box#235]
As people have started posting requests for v3.0, here my ones (by now):
1. Re-adding of Acer V12LC motherboard (it was available back in PCem-X)
2. Ability of change of model of emulated CD-ROM (including ability to change Vendor ID, etc.)

**Comment by OBattler** [comment]
I'm going to look at this for 86Box v3.0.

**Comment by OBattler** [comment]
Currently, the roadmap has changed to include v2.10 before v3.00, and point 1 of this request will probably be doable for v2.10. So I'm closing this issue until v2.00 is released.

**Comment by OBattler** [comment]
The Acer V12LC is no go - it uses ALi chips and finding datasheets for those is essentially impossible.

**Comment by ArtiomWin** [comment]
You mean this ones?
https://mega.nz/#!MVM1UTJK!_7dp9G7KZEVtFJ6LqOSPGyyeOK8zTMd0dNc508l7VlY

**Comment by waltje** [comment]
Which ALi chipset is used in this board?

**Comment by ArtiomWin** [comment]
@waltje It was a bit hard to find, but that chipset is ALi M1451/1459. And yes, there are problems with datasheets (for ALi, i've found ones for M1489 and ALADDiN series).

**Comment by waltje** [comment]
Ah, OK

We really need one for the 1429 ... isnt that Aladdin as well?

--fred

--------------------------------------------
On Wed, 5/23/18, ArtiomWin <notifications@github.com> wrote:

 Subject: Re: [86Box/86Box] Requests - January 2018 (#235)
 To: "86Box/86Box" <86Box@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Wednesday, May 23, 2018, 4:04 PM
 
 @waltje It was a bit
 hard to find, but that chipset is ALi M1451/1459. And yes,
 there are problems with datasheets (for ALi, i've found
 ones for M1489 and ALADDiN series).
 
 —
 You are
 receiving this because you were mentioned.
 Reply to
 this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by ArtiomWin** [comment]
No, earliest known ALADDiN chipsets are based on Pentium and Socket 7.
