### ISSUE TITLE
AMI 286 board reports 384Kb too much RAM

### ISSUE THREAD

**Issue by Altheos** [OBattler/86Box#245]
Config : 
AMI 286, 286 6 Mhz, 640 Kb RAM, VGA 8bit.

Boot counted RAM : 1024 Kb (1Mb). 
Boot : Bank 0/1 DRAM = 1 Mb Type.
Reported RAM by BIOS : 640 Kb / 0 Kb extended.

With 512 kb RAM : 
Boot counted RAM : 896 Kb.

**Comment by OBattler** [comment]
I suspect this is actually a BIOS bug - the machine uses the NEAT chipset which does *NOT* remap the top 384k, which means a memory count would always be 384k lower than the actual size, and the BIOS just adds 384k to the count to compensate for that, but because it's buggy, it does that even when the machine has less than 1 MB of RAM. So I am closing this issue for being a BIOS bug.
