### ISSUE TITLE
8086/8088 XT bug with DOS 2.1

### ISSUE THREAD

**Issue by Fenix770** [OBattler/86Box#249]
Hello

I  discovered (in PCem) a nasty bug. (I report here because it seems both branches use the same CPU emulation)  with several software, when MS-DOS/PC-DOS 2.11 is used in 8086/8088 machines. The issue does not happen when the configuration is a 286 CPU with any DOS or an XT machine with DOS 3.2 or later.  I Tested PC-DOS 2.10 on 8086/8088 machines, Tandy 1000 HX and Toshiba T1000 (in PCEM) ROM DOS. 

Also when I try to boot PC-DOS 3.0 on any XT I get a "Disk boot failure", but works on 286.
(Tested with same floppy image) 

List of Working and not working software on XT and DOS 2.1:

**Not Working:**
Pictionary (1989): when i execute piction.exe the game crash instantly. (except if mouse.sys is loaded in memory). Works on IBM AT 286 with DOS 2.1 even if no mouse driver is loaded.

-FreeDOS Edit and MEM external command locks the system. The only solution it's reboot (works on DOS 3.3)

-4DOS version 2.21 (Shareware 1989, it's not the freeware 4DOS 8.00) 4dos88.exe works but 4dos.com lock's up the system too. (works on  DOS 3.3)

**Working**

-Tetris (Spectrum Holobyte 1989)
-Welltris 
-Outrun
-Block 'o Mania: Block.exe generates and exception but cgablock.exe works. The game works too (i played until level 5).

It seems to me that there's some bug on 8086/8088 CPU emulation, and I don't know if its related to slowdown bug with Prince of Persia  I previously reported. This game has this issue with any DOS version under any XT machine.

**Comment by OBattler** [comment]
On DOS 2.x, 4DOS.COM hangs when executing the INT 2Fh call to check if 4DOS is already installed, because DOS 2.x does not install an INT 2Fh handler at all so that interrupt remains pointing at whatever the BIOS points it at, and on most such early machines, that's 0000:0000 which is invalid (it's the beginning of the interrupt vector table itself), hence the hang.

Could you upload Pictionary somewhere please so I can test it and see why it crashes.

As for FreeDOS, I'm going to look into that, though something tells me FreeDOS is not really 808x-compatible.

**Comment by OBattler** [comment]
FreeDOS MEM and EDIT also call INT 2Fh and EDIT in addition also calls INT 33h, which also has a 0000:0000 vector on DOS 2.x on PC/XT.
This is my small program that installs stub handlers (that only do an IRET) for both INT 2Fh and INT 33h, which makes all three programs work: http://citadel.ringoflightning.net/FAKE2F.rar .
Now just waiting for your upload of Pictionary so I can see what causes that to crash.

**Comment by Fenix770** [comment]
Hello.
I uploaded the zipped file img file format. (created with Winimage 9)
[https://drive.google.com/file/d/1UdrGeMHyMSCMruivABCmk0-BDDUBCT-j/view?usp=sharing](url).
Also I attach this screenshot. (It's an XT machine with PC-DOS 2.10)
![screenshot from 2018-01-18 12-48-39](https://user-images.githubusercontent.com/31600563/35486774-8df013de-0451-11e8-9088-eb3ad4700e33.png)

**Comment by OBattler** [comment]
OK, turns out Pictionary calls INT 33h, and I just tested - my little program that I linked above, makes that work too. As such, I can close this now, since it's not an emulator bug but a behavior resulting from a combination of PC/XT and DOS 2.x which leaves some interrupt handlers have 0000:0000 vectors, resulting in these problems and I have provided a little program that works around that by installing stub handlers for INT 2Fh and INT 33h.

**Comment by OBattler** [comment]
Also, make sure you run FAKE2F *before* the mouse driver, as the mouse driver also hooks INT 33h (in fact, that is I think the mouse interrupt), so if you run FAKE2F after the mouse driver, it will make the mouse driver unusable.
